# Generated by Django 4.1.5 on 2023-05-16 20:05

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wblog', '0003_allproducts_delete_allproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='prod_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='prod_name', unique=True),
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_addres', models.CharField(max_length=500)),
                ('user_landnark', models.CharField(max_length=50)),
                ('user_phone', models.IntegerField()),
                ('user_pincode', models.CharField(max_length=50)),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
