# Generated by Django 4.1.5 on 2023-05-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wblog', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='prod_rating',
            field=models.IntegerField(null=True),
        ),
    ]
